// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  addonpacks: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
